Pizza_Assingnment/Models/PizzaMenu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Pizza_Assingnment.Models
{
    //public class named PizzaMenu
    public class PizzaMenu
    {
        //variables with get and set
        public int Id { set; get; }
        [Required]
        public string Name { set; get; }
        [Required]
        public string Toppings { set; get; }
        [Required]
        public int Price { set; get; }
    }
}

Pizza_Assingnment/Controllers/DrinkMenuController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Pizza_Assingnment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pizza_Assingnment.Controllers
{
    public class DrinkMenuController : Controller
    {
        DrinkMenuDataAccessLayer drinkMenuDataAccessLayer = null;
        public DrinkMenuController()
        {
            drinkMenuDataAccessLayer = new DrinkMenuDataAccessLayer();
        }

        // GET: DrinkMenuController
        public ActionResult Index()
        {
            IEnumerable<DrinkMenu> drinkMenus = drinkMenuDataAccessLayer.GetAllDrinkMenu();
            return View(drinkMenus);
        }

        // GET: DrinkMenuController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DrinkMenuController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DrinkMenuController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DrinkMenuController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DrinkMenuController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DrinkMenuController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DrinkMenuController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Pizza_Assingnment/Controllers/PizzaMenuController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Pizza_Assingnment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pizza_Assingnment.Controllers
{
    public class PizzaMenuController : Controller
    {
        PizzaMenuDataAccessLayer pizzaMenuDataAccessLayer = null;
        public PizzaMenuController()
        {
            pizzaMenuDataAccessLayer = new PizzaMenuDataAccessLayer();
        }

        // GET: PizzaMenuController
        public ActionResult Index()
        {
            IEnumerable<PizzaMenu> pizzaMenus = pizzaMenuDataAccessLayer.GetAllPizzaMenu();
            return View(pizzaMenus);
        }

        // GET: PizzaMenuController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PizzaMenuController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PizzaMenuController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PizzaMenuController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PizzaMenuController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PizzaMenuController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PizzaMenuController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Pizza_Assingnment/Views/PizzaMenu/Index.cshtml
@model IEnumerable<Pizza_Assingnment.Models.PizzaMenu>

@{
    ViewData["Title"] = "Menu";
}

<section class="MenuSection">
    <h1>Menu - Pizza</h1>

    <div class="MenuOption">
        <div>
            <a class="active" asp-area="" asp-controller="PizzaMenu" asp-action="Index">Pizza</a>
            <a asp-area="" asp-controller="DrinkMenu" asp-action="Index">Drikkevare</a>
        </div>
        <input type="text" id="searchInput" onkeyup="searchFunction()" placeholder="Søg" />
    </div>

<table class="table" id="table">
    <thead>
        <tr class="header">
            <th>
                Number
            </th>
            <th>
                Navn
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Toppings)
            </th>
            <th>
                Priser
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Toppings)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                </tr>
        }
        </tbody>
</table>
</section>